//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShop.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int ImgId { get; set; }
        public string ImgUrl { get; set; }
        public int productId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
