//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShop.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartPhone
    {
        public int Id { get; set; }
        public int product_id { get; set; }
        public string model_number { get; set; }
        public string screen_size { get; set; }
        public string weight { get; set; }
        public string dimension { get; set; }
        public string processor { get; set; }
        public string ram { get; set; }
        public string storage { get; set; }
        public string colour { get; set; }
        public string primary_camera { get; set; }
        public string secondary_camera { get; set; }
        public string network_type { get; set; }
    }
}
